[project]
name = "document-portal"
version = "0.1.0"
description = "This is a RAG (Retrieval-Augmented Generation) system for document querying, allowing users to upload documents and interact with them using natural language queries powered by various AI models."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Rahul Samant"},
]
dependencies = [
    "langchain",
    "python-dotenv",
    "ipykernel",
    "langchain_groq",
    "langchain_google_genai",
    "langchain-community>=0.3.27",
    "pypdf>=5.8.0",
    "faiss-cpu>=1.11.0.post1",
    "structlog>=25.4.0",
    "pymupdf>=1.26.3",
    "pyyaml>=6.0.2",
    "pandas>=2.3.1",
    "streamlit>=1.48.1",
    "docx2txt>=0.9",
    "fastapi[standard]>=0.116.1",
    "uvicorn>=0.35.0",
    "python-multipart>=0.0.20",
    "plotly>=6.3.0",
    "setuptools>=80.9.0",
]

[project.optional-dependencies]
dev = ["mypy>=1.11.1", "ruff>=0.6.1"]

[project.scripts]
document-portal = "main:main"
document-portal-api = "app:main"

[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Use find packages to automatically discover all packages
packages = {find = {}}

[tool.setuptools.package-data]
"*" = ["py.typed", "*.yaml", "*.yml", "*.json", "*.txt", "*.md"]

[tool.ruff]
lint.select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "D",    # pydocstyle
    "D401", # First line should be in imperative mood
    "T201",
    "UP",
]
lint.ignore = [
    "UP006",
    "UP007",
    "UP035",
    "D417",
    "E501",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "UP"]

[tool.ruff.lint.pydocstyle]
convention = "google"