[project]
name = "document-portal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain",
    "python-dotenv",
    "ipykernel",
    "langchain_groq",
    "langchain_google_genai",
    "langchain-community>=0.3.27",
    "pypdf>=5.8.0",
    "faiss-cpu>=1.11.0.post1",
    "structlog>=25.4.0",
    "pymupdf>=1.26.3",
    "pyyaml>=6.0.2",
    "pandas>=2.3.1",
    "streamlit>=1.48.1",
    "docx2txt>=0.9",
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
    "python-multipart>=0.0.20",
    "plotly>=6.3.0",
]
