faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "google"
  model_name: "model/text-embedding-004"

retriever:
  top_k: 10

llm:
  provider: "google"
  model_name: "gemini-2.0-flash"
  temperature: 0
  max_output_tokens: 2048